### ISSUE TITLE
model_large_retrieval_coco.pth

### ISSUE THREAD

**Issue by qianhe-666** [CuriseJia/FreeStyleRet#36]
model_large_retrieval_coco.pth这个文件在哪里，没有找到

**Comment by CuriseJia** [comment]
Hi, 这是BLIP的预训练权重。可以从https://github.com/salesforce/BLIP下载，祝好！

**Comment by qianhe-666** [comment]
感谢

**Comment by Ran2115** [comment]
Hello, I used the pre trained weights provided in the link, but encountered the following error. How can I solve it? thank you
RuntimeError: Error(s) in loading state_dict for CLIP:
	Missing key(s) in state_dict: "positional_embedding", "text_projection", "logit_scale", "visual.class_embedding", "visual.positional_embedding", "visual.proj", "visual.conv1.weight", "visual.ln_pre.weight", "visual.ln_pre.bias", 
	Unexpected key(s) in state_dict: "model".
