### ISSUE TITLE
准确率不高

### ISSUE THREAD

**Issue by qianhe-666** [CuriseJia/FreeStyleRet#37]
这位是我运行的结果：
(free) user@user:~/qh/freestyleret$ python test.py --resume /home/user/qh/freestyleret/output/DeepPrompt_s2i.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [04:19<00:00,  1.04s/it]
R@1 Acc is 0.125
R@5 Acc is 0.5
在我运行期间，损失率一直是loss: 1.000000，训练轮数为5，我尝试更改训练轮数依旧没有反应，想问一下我这个是哪里出了问题。

**Comment by CuriseJia** [comment]
I'm not sure why the bugs happened, maybe you can change some experiment settings?

**Comment by Jacknegar** [comment]
你好，我在训练sketch到image的过程中使用DeepPrompt的损失率loss也一直是1.000，使用text2image,DeepPrompt的损失率一直在1到1.1波动。
