### ISSUE TITLE
 style_cluster.npy 

### ISSUE THREAD

**Issue by Jacknegar** [CuriseJia/FreeStyleRet#38]
Hello！I did not find the style_cluster.npy file, is it convenient to tell the location or download link?

**Comment by qianhe-666** [comment]
这个文件是运行freestyleret/src/dataset/gen_cluster.py自动生成的

**Comment by zihan912** [comment]
> 这个文件是运行freestyleret/src/dataset/gen_cluster.py自动生成的

我运行的时候在'from open_clip.factory' import image_transform‘时报错了，显示没有这个这个函数，也确实没有在factory.py中找到，请问这个问题怎么解决呢

**Comment by Jacknegar** [comment]
在factory.py文件中，用了image_transformv2，但是这个v2只能传递三个参数，你可以将image_transfrom中的四个参数按照v2传入的参数整理一下。
你也可以尝试在factory.py文件中增加image_tansfrom的调用，两种方案都可以。






 ----------Reply to Message----------
 On Sat, Sep 21, 2024 21:09 PM ***@***.***&gt; wrote:

  

  
这个文件是运行freestyleret/src/dataset/gen_cluster.py自动生成的
  
我运行的时候在'from open_clip.factory' import image_transform‘时报错了，显示没有这个这个函数，也确实没有在factory.py中找到，请问这个问题怎么解决呢

**Comment by shineway14** [comment]
> 这个文件是运行freestyleret/src/dataset/gen_cluster.py自动生成的

gen_cluster.py报错Found array with dim3 .KMeans expected<=2
请问有遇到这个报错吗
