### ISSUE TITLE
model_large_retrieval_coco.pth

### ISSUE THREAD

**Issue by Ran2115** [CuriseJia/FreeStyleRet#40]
Hello, I used the pre-trained weights model_large_retrieval_coco.pth provided in the link, but encountered the following error. How can I solve it? thank you
RuntimeError: Error(s) in loading state_dict for CLIP:
Missing key(s) in state_dict: "positional_embedding", "text_projection", "logit_scale", "visual.class_embedding", "visual.positional_embedding", "visual.proj", "visual.conv1.weight", "visual.ln_pre.weight", "visual.ln_pre.bias",
Unexpected key(s) in state_dict: "model".

**Comment by CuriseJia** [comment]
This ckpt file is used for BLIP, thanks.
