### ISSUE TITLE
about the original resume

### ISSUE THREAD

**Issue by LighteningDarkness** [CuriseJia/FreeStyleRet#41]
excellent work! and could you please give me some advice on how to set the value of original resume when I use DeepPrompt. thank you!

**Comment by CuriseJia** [comment]
Hi, I'm not sure about the value, you mean the seed or some other parameters?

**Comment by LighteningDarkness** [comment]
呃抱歉没讲清楚，就是open clip支持的模型不是有一个列表嘛，我把original_resume设为openai时能运行起来，但是指标好像一般般（我自己做了些改动，不过应该这边没问题），所以就想问下您这边模型选用哪个

**Comment by CuriseJia** [comment]
you can try the laion or datacamp pretrained
